/**
 * Complete Template Import Schema
 * 
 * This comprehensive schema documents all available placeholders, configuration options,
 * sample data, and examples for building email templates externally and importing them.
 */

export const TEMPLATE_IMPORT_SCHEMA = {
  "$schema": "Template Import Schema v2",
  "description": "JSON schema for importing email templates with event data placeholders",
  
  "event_placeholders": {
    "description": "Available placeholders for use in html_template and quick_share_template. Use double curly braces: {{placeholder}}",
    "core_fields": {
      "{{eventName}}": "Full event name/title",
      "{{eventTitle}}": "Alias for eventName",
      "{{venue}}": "Venue name",
      "{{venueAddress}}": "Full venue address",
      "{{city}}": "City name",
      "{{state}}": "State code (e.g., CA, NY)",
      "{{cityState}}": "Combined city, state (e.g., Los Angeles, CA)"
    },
    "date_time_fields": {
      "{{eventDate}}": "Formatted date (e.g., Saturday, January 21, 2025)",
      "{{eventDateShort}}": "Short date (e.g., Jan 21)",
      "{{eventTime}}": "Formatted time (e.g., 7:30 PM)",
      "{{eventDay}}": "Day of week (e.g., Saturday)",
      "{{eventDayShort}}": "Short day (e.g., Sat)",
      "{{eventWeekday}}": "Alias for eventDay",
      "{{eventMonth}}": "Month name (e.g., January)",
      "{{eventMonthShort}}": "Short month (e.g., Jan)",
      "{{eventMonthYear}}": "Month + Year (e.g., January 2025)",
      "{{eventDayNum}}": "Day number (e.g., 21)",
      "{{eventYear}}": "Year (e.g., 2025)",
      "{{eventDatetime}}": "Full datetime (e.g., Sat Jan 21, 2025 at 7:30 PM)"
    },
    "media_fields": {
      "{{imageUrl}}": "Primary event image URL (CDN optimized)",
      "{{seatmapUrl}}": "Venue seatmap image URL",
      "{{performerImage}}": "Performer/artist image URL",
      "{{homeTeamLogo}}": "Home team logo URL (sports)",
      "{{awayTeamLogo}}": "Away team logo URL (sports)",
      "{{performerPhoto}}": "Wikipedia performer photo URL"
    },
    "pricing_fields": {
      "{{priceMin}}": "Minimum ticket price (e.g., $85)",
      "{{priceMax}}": "Maximum ticket price (e.g., $450)",
      "{{priceRange}}": "Price range (e.g., $85 - $450)",
      "{{priceAvg}}": "Average ticket price"
    },
    "link_fields": {
      "{{ticketLink}}": "Direct ticket purchase URL (First Class Tixx)",
      "{{websiteUrl}}": "First Class Tixx website page URL",
      "{{ctaLink}}": "CTA button link (configurable)",
      "{{conciergeEmail}}": "Email concierge mailto link with event details",
      "{{eventCode}}": "Unique event code for reference",
      "{{venueMapUrl}}": "Google Maps link to venue"
    },
    "sports_specific": {
      "{{teamHome}}": "Home team name",
      "{{teamAway}}": "Away team name",
      "{{opponent}}": "Just the opponent team name",
      "{{league}}": "League (NBA, NFL, MLB, NHL, etc.)",
      "{{sport}}": "Sport type (basketball, football, etc.)",
      "{{matchup}}": "Formatted matchup (e.g., Lakers vs Warriors)",
      "{{teamHomePrimaryColor}}": "Home team primary color hex",
      "{{teamHomeSecondaryColor}}": "Home team secondary color hex",
      "{{teamAwayPrimaryColor}}": "Away team primary color hex",
      "{{teamAwaySecondaryColor}}": "Away team secondary color hex"
    },
    "concert_specific": {
      "{{performerPrimary}}": "Main artist/performer name",
      "{{performerSecondary}}": "Opening act or supporting artist",
      "{{tourName}}": "Tour name if applicable",
      "{{performerBio}}": "Wikipedia-sourced performer biography",
      "{{genre}}": "Music genre"
    },
    "comedy_specific": {
      "{{comedianName}}": "Comedian name",
      "{{opener}}": "Opening comedian",
      "{{showType}}": "Show type (standup, improv, podcast, etc.)",
      "{{ageRestriction}}": "Age restriction (18+, 21+, all-ages)",
      "{{contentWarning}}": "Content warning if applicable",
      "{{isRecordingDate}}": "Whether this is a recording/filming date"
    },
    "add_on_specific": {
      "{{parentEventName}}": "Main event this add-on is for",
      "{{addOnType}}": "Type of add-on (parking, wristband, etc.)",
      "{{lotName}}": "Parking lot name",
      "{{lotLocation}}": "Parking lot location/directions",
      "{{accessAreas}}": "VIP access areas included",
      "{{validDays}}": "Days the add-on is valid",
      "{{upgradeIncludes}}": "What the upgrade includes",
      "{{shuttleSchedule}}": "Shuttle pickup times/schedule",
      "{{requiresMainTicket}}": "Whether main event ticket is required"
    },
    "group_template_fields": {
      "{{eventCount}}": "Number of events in group",
      "{{groupTitle}}": "Group header (e.g., Los Angeles Lakers Home Games)",
      "{{groupSlate}}": "Slate label (e.g., 3 Upcoming Home Games)",
      "{{dateRange}}": "Date range of grouped events (e.g., Jan 21 - Mar 15)",
      "{{customBlurb}}": "Custom marketing blurb for the group",
      "{{#each events}}...{{/each}}": "Loop through events in a group template"
    }
  },

  "sample_event_data": {
    "sports_game": {
      "eventName": "Los Angeles Lakers vs Golden State Warriors",
      "venue": "Crypto.com Arena",
      "venueAddress": "1111 S Figueroa St, Los Angeles, CA 90015",
      "city": "Los Angeles",
      "state": "CA",
      "cityState": "Los Angeles, CA",
      "eventDate": "Saturday, January 25, 2025",
      "eventDateShort": "Jan 25",
      "eventTime": "7:30 PM",
      "eventDay": "Saturday",
      "eventDayShort": "Sat",
      "eventWeekday": "Saturday",
      "eventMonth": "January",
      "eventMonthShort": "Jan",
      "eventMonthYear": "January 2025",
      "eventDayNum": "25",
      "eventYear": "2025",
      "eventDatetime": "Sat Jan 25, 2025 at 7:30 PM",
      "imageUrl": "https://cdn.firstclasstixx.com/events/lakers-warriors.jpg",
      "seatmapUrl": "https://cdn.firstclasstixx.com/seatmaps/crypto-arena.jpg",
      "homeTeamLogo": "https://cdn.firstclasstixx.com/logos/lakers.png",
      "awayTeamLogo": "https://cdn.firstclasstixx.com/logos/warriors.png",
      "priceMin": "$125",
      "priceMax": "$2,500",
      "priceRange": "$125 - $2,500",
      "priceAvg": "$485",
      "ticketLink": "https://firstclasstixx.com/events/lakers-warriors-jan25",
      "websiteUrl": "https://firstclasstixx.com/lakers",
      "venueMapUrl": "https://maps.google.com/?q=Crypto.com+Arena",
      "eventCode": "LAL-GSW-0125",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Lakers%20vs%20Warriors%20-%20Jan%2025",
      "teamHome": "Los Angeles Lakers",
      "teamAway": "Golden State Warriors",
      "opponent": "Warriors",
      "league": "NBA",
      "sport": "basketball",
      "matchup": "Lakers vs Warriors",
      "teamHomePrimaryColor": "#552583",
      "teamHomeSecondaryColor": "#FDB927",
      "teamAwayPrimaryColor": "#1D428A",
      "teamAwaySecondaryColor": "#FFC72C",
      "groupSlate": "3 Upcoming Home Games"
    },
    "concert": {
      "eventName": "Taylor Swift | The Eras Tour",
      "venue": "SoFi Stadium",
      "venueAddress": "1001 Stadium Dr, Inglewood, CA 90301",
      "city": "Inglewood",
      "state": "CA",
      "cityState": "Inglewood, CA",
      "eventDate": "Friday, August 15, 2025",
      "eventDateShort": "Aug 15",
      "eventTime": "6:30 PM",
      "eventDay": "Friday",
      "eventDayShort": "Fri",
      "eventWeekday": "Friday",
      "eventMonth": "August",
      "eventMonthShort": "Aug",
      "eventMonthYear": "August 2025",
      "eventDayNum": "15",
      "eventYear": "2025",
      "eventDatetime": "Fri Aug 15, 2025 at 6:30 PM",
      "imageUrl": "https://cdn.firstclasstixx.com/events/taylor-swift-eras.jpg",
      "performerImage": "https://cdn.firstclasstixx.com/artists/taylor-swift.jpg",
      "performerPhoto": "https://upload.wikimedia.org/wikipedia/commons/taylor-swift.jpg",
      "seatmapUrl": "https://cdn.firstclasstixx.com/seatmaps/sofi-stadium.jpg",
      "priceMin": "$350",
      "priceMax": "$8,500",
      "priceRange": "$350 - $8,500",
      "priceAvg": "$1,250",
      "ticketLink": "https://firstclasstixx.com/events/taylor-swift-sofi-aug15",
      "websiteUrl": "https://firstclasstixx.com/concerts/taylor-swift",
      "venueMapUrl": "https://maps.google.com/?q=SoFi+Stadium",
      "eventCode": "TS-ERAS-0815",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Taylor%20Swift%20Eras%20Tour%20-%20Aug%2015",
      "performerPrimary": "Taylor Swift",
      "performerSecondary": "Gracie Abrams",
      "tourName": "The Eras Tour",
      "performerBio": "Taylor Swift is an American singer-songwriter known for narrative songs about her personal life...",
      "genre": "Pop"
    },
    "comedy_show": {
      "eventName": "Dave Chappelle Live",
      "venue": "Hollywood Bowl",
      "venueAddress": "2301 N Highland Ave, Los Angeles, CA 90068",
      "city": "Los Angeles",
      "state": "CA",
      "cityState": "Los Angeles, CA",
      "eventDate": "Saturday, June 14, 2025",
      "eventDateShort": "Jun 14",
      "eventTime": "8:00 PM",
      "eventDay": "Saturday",
      "eventDayShort": "Sat",
      "eventWeekday": "Saturday",
      "eventMonth": "June",
      "eventMonthShort": "Jun",
      "eventMonthYear": "June 2025",
      "eventDayNum": "14",
      "eventYear": "2025",
      "eventDatetime": "Sat Jun 14, 2025 at 8:00 PM",
      "imageUrl": "https://cdn.firstclasstixx.com/events/dave-chappelle.jpg",
      "performerPhoto": "https://upload.wikimedia.org/wikipedia/commons/dave-chappelle.jpg",
      "seatmapUrl": "https://cdn.firstclasstixx.com/seatmaps/hollywood-bowl.jpg",
      "priceMin": "$175",
      "priceMax": "$950",
      "priceRange": "$175 - $950",
      "priceAvg": "$325",
      "ticketLink": "https://firstclasstixx.com/events/chappelle-hollywood-bowl",
      "websiteUrl": "https://firstclasstixx.com/comedy/dave-chappelle",
      "venueMapUrl": "https://maps.google.com/?q=Hollywood+Bowl",
      "eventCode": "DC-HB-0614",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Dave%20Chappelle%20-%20Jun%2014",
      "comedianName": "Dave Chappelle",
      "opener": "Donnell Rawlings",
      "showType": "standup",
      "ageRestriction": "18+",
      "contentWarning": "Adult language and themes",
      "isRecordingDate": false
    },
    "festival": {
      "eventName": "Coachella Valley Music and Arts Festival 2025",
      "venue": "Empire Polo Club",
      "venueAddress": "81800 Avenue 51, Indio, CA 92201",
      "city": "Indio",
      "state": "CA",
      "cityState": "Indio, CA",
      "eventDate": "Friday, April 11, 2025",
      "eventDateShort": "Apr 11",
      "eventTime": "12:00 PM",
      "eventDay": "Friday",
      "eventDayShort": "Fri",
      "eventWeekday": "Friday",
      "eventMonth": "April",
      "eventMonthShort": "Apr",
      "eventMonthYear": "April 2025",
      "eventDayNum": "11",
      "eventYear": "2025",
      "eventDatetime": "Fri Apr 11, 2025 at 12:00 PM",
      "imageUrl": "https://cdn.firstclasstixx.com/events/coachella-2025.jpg",
      "seatmapUrl": "https://cdn.firstclasstixx.com/maps/coachella-grounds.jpg",
      "priceMin": "$549",
      "priceMax": "$12,500",
      "priceRange": "$549 - $12,500",
      "priceAvg": "$1,850",
      "ticketLink": "https://firstclasstixx.com/events/coachella-2025-weekend1",
      "websiteUrl": "https://firstclasstixx.com/festivals/coachella",
      "venueMapUrl": "https://maps.google.com/?q=Empire+Polo+Club",
      "eventCode": "COACH-W1-2025",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Coachella%202025%20Weekend%201",
      "dateRange": "April 11-13, 2025"
    },
    "add_on_parking": {
      "addOnType": "vip-parking",
      "parentEventName": "Lakers vs Warriors - Jan 25",
      "lotName": "Lot W VIP",
      "lotLocation": "West entrance, closest to player entrance",
      "venue": "Crypto.com Arena",
      "venueAddress": "1111 S Figueroa St, Los Angeles, CA 90015",
      "city": "Los Angeles",
      "state": "CA",
      "cityState": "Los Angeles, CA",
      "eventDate": "Saturday, January 25, 2025",
      "eventTime": "7:30 PM",
      "eventDayShort": "Sat",
      "priceMin": "$75",
      "priceMax": "$150",
      "ticketLink": "https://firstclasstixx.com/add-ons/lakers-parking-jan25",
      "websiteUrl": "https://firstclasstixx.com/parking/crypto-arena",
      "venueMapUrl": "https://maps.google.com/?q=Crypto.com+Arena+Parking",
      "eventCode": "LAL-PARK-0125",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Lakers%20VIP%20Parking%20-%20Jan%2025",
      "requiresMainTicket": true
    },
    "add_on_wristband": {
      "addOnType": "wristband-vip",
      "parentEventName": "Coachella 2025 Weekend 1",
      "accessAreas": "VIP Village, Rose Garden, VIP Viewing Areas",
      "validDays": "Friday, Saturday, Sunday",
      "upgradeIncludes": "Exclusive viewing areas, premium restrooms, dedicated bars, VIP-only experiences",
      "venue": "Empire Polo Club",
      "city": "Indio",
      "state": "CA",
      "cityState": "Indio, CA",
      "eventDate": "April 11-13, 2025",
      "priceMin": "$1,200",
      "priceMax": "$2,500",
      "ticketLink": "https://firstclasstixx.com/add-ons/coachella-vip-wristband",
      "websiteUrl": "https://firstclasstixx.com/festivals/coachella/vip",
      "eventCode": "COACH-VIP-W1",
      "conciergeEmail": "mailto:concierge@firstclasstixx.com?subject=Coachella%20VIP%20Wristband",
      "requiresMainTicket": true
    },
    "add_on_shuttle": {
      "addOnType": "shuttle",
      "parentEventName": "Coachella 2025 Weekend 1",
      "venue": "Empire Polo Club",
      "city": "Indio",
      "state": "CA",
      "shuttleSchedule": "Departures every 30 min from Palm Springs (10am-2pm), Returns until 2am",
      "validDays": "Friday, Saturday, Sunday",
      "priceMin": "$85",
      "ticketLink": "https://firstclasstixx.com/add-ons/coachella-shuttle",
      "eventCode": "COACH-SHUTTLE-W1",
      "requiresMainTicket": true
    },
    "group_events": {
      "groupTitle": "Los Angeles Lakers Home Games",
      "groupSlate": "5 Upcoming Home Games",
      "eventCount": 5,
      "dateRange": "Jan 15 - Feb 28, 2025",
      "customBlurb": "Don't miss the Lakers at home this season! Premium seats available for all matchups.",
      "events": [
        {
          "eventName": "Lakers vs Warriors",
          "eventDateShort": "Jan 25",
          "eventDayShort": "Sat",
          "eventTime": "7:30 PM",
          "opponent": "Warriors",
          "matchup": "Lakers vs Warriors",
          "priceMin": "$125"
        },
        {
          "eventName": "Lakers vs Clippers",
          "eventDateShort": "Feb 1",
          "eventDayShort": "Sat",
          "eventTime": "7:30 PM",
          "opponent": "Clippers",
          "matchup": "Lakers vs Clippers",
          "priceMin": "$145"
        },
        {
          "eventName": "Lakers vs Celtics",
          "eventDateShort": "Feb 15",
          "eventDayShort": "Sat",
          "eventTime": "5:00 PM",
          "opponent": "Celtics",
          "matchup": "Lakers vs Celtics",
          "priceMin": "$225"
        }
      ]
    }
  },

  "template_config_options": {
    "description": "Available configuration options for the config object",
    "typography": {
      "fontHeading": "Google Font name for headings (e.g., 'Oswald', 'Bebas Neue')",
      "fontBody": "Google Font name for body text (e.g., 'DM Sans', 'Inter')",
      "fontSizeTitle": "Title font size in pixels (default: 28)",
      "fontSizeBody": "Body font size in pixels (default: 14)",
      "fontSizeSubtitle": "Subtitle font size in pixels (default: 18)",
      "letterSpacing": "Letter spacing in em units (default: 0)",
      "lineHeight": "Line height multiplier (default: 1.5)",
      "titleColorMode": "'auto' | 'dark' | 'light' | 'gray' | 'custom'",
      "bodyColorMode": "'auto' | 'dark' | 'light' | 'gray' | 'custom'",
      "titleSize": "'auto' | 'sm' | 'md' | 'lg' | 'xl'",
      "titleFillRow": "Whether title should span full width (boolean)",
      "fontPairing": "Preset font pairing name"
    },
    "colors": {
      "backgroundColor": "Background color hex (e.g., '#1a1a1a')",
      "textColor": "Main text color hex",
      "accentColor": "Accent/highlight color hex",
      "ctaBackgroundColor": "CTA button background color",
      "ctaTextColor": "CTA button text color",
      "borderColor": "Border color hex",
      "glowColor": "Glow effect color (for neon styles)",
      "gradientStart": "Gradient start color",
      "gradientEnd": "Gradient end color"
    },
    "background_frame": {
      "bgPreset": "'light' | 'dark' | 'transparent' | 'custom'",
      "backgroundTransparent": "Make background transparent (boolean)",
      "innerBorderEnabled": "Enable inner border frame (boolean)",
      "innerBorderColor": "Inner border color hex",
      "innerBorderWidth": "Inner border width in pixels",
      "innerBorderInset": "Inner border inset/padding in pixels",
      "blockShadow": "'none' | 'soft' | 'medium' | 'deep'",
      "blockShadowColor": "Shadow color with opacity"
    },
    "sports_frame": {
      "enableSportsFrame": "Enable team-colored double border frame (boolean)",
      "sportsAutoPalette": "Auto-detect team colors from event (boolean)",
      "sportsOuterColor": "Outer border color (team primary)",
      "sportsOuterAltColor": "Outer border alternate color (team secondary)",
      "sportsInnerColor": "Inner border color",
      "sportsCornerRadius": "Corner radius in pixels",
      "sportsGapThickness": "Gap between borders in pixels",
      "sportsUseGradient": "Use gradient for borders (boolean)"
    },
    "layout": {
      "padding": "Content padding in pixels (default: 24)",
      "margin": "Outer margin in pixels (default: 16)",
      "borderWidth": "Border width in pixels (default: 0)",
      "borderRadius": "Border radius in pixels (default: 8)",
      "shadowIntensity": "Shadow intensity 0-100 (default: 0)",
      "columnLayout": "'single' | 'two' | 'three' | 'grid'",
      "cardStyle": "'flat' | 'elevated' | 'neon' | 'glass' | 'brutalist' | 'ticket'"
    },
    "visibility": {
      "showImages": "Show event images (boolean)",
      "showTimes": "Show event times (boolean)",
      "showVenue": "Show venue info (boolean)",
      "showCta": "Show CTA button (boolean)",
      "showConciergeLink": "Show concierge email link (boolean)",
      "showPrices": "Show ticket prices (boolean)",
      "showMatchup": "Show team matchup (sports) (boolean)",
      "showHeaderDetail": "Show header detail line (boolean)",
      "heroImageMode": "'auto' | 'landscape' | 'portrait' | 'none'",
      "showSecondaryImages": "Show secondary/supporting images (boolean)",
      "showTimeInHeader": "Show time in header area (boolean)",
      "showTimePerRow": "Show time for each event row (boolean)",
      "collapseIdenticalTimes": "Collapse rows with same time (boolean)",
      "showSlateLabel": "Show slate/group label (boolean)"
    },
    "cta_primary": {
      "ctaText": "CTA button text (default: 'Get Tickets')",
      "ctaLink": "CTA button link URL",
      "ctaEnabled": "Enable main CTA button (boolean)",
      "eventCtaEnabled": "Enable per-event CTA links (boolean)",
      "eventUnderline": "Underline event links (boolean)",
      "eventIcon": "Show icon on event links (boolean)"
    },
    "cta_dual": {
      "description": "Independent controls for Tickets CTA and Email CTA in group templates",
      "showTicketsCta": "Show tickets CTA link (boolean, default: true)",
      "ticketsCtaText": "Tickets CTA text (default: 'View Tickets')",
      "ticketsCtaStyle": "'link' | 'button' | 'pill' | 'underline' (default: 'link')",
      "ticketsCtaIcon": "Show arrow icon on tickets CTA (boolean, default: true)",
      "showEmailCta": "Show email CTA link (boolean, default: true)",
      "emailCtaText": "Email CTA text (default: 'Email')",
      "emailCtaStyle": "'link' | 'button' | 'pill' | 'underline' (default: 'link')",
      "emailCtaIcon": "Show envelope icon on email CTA (boolean, default: false)"
    },
    "cta_concierge": {
      "conciergeLabel": "Concierge link text (default: 'Email Concierge')",
      "conciergeNoUrlLabel": "Concierge text when no URL available",
      "conciergeColor": "Concierge link color",
      "conciergeUnderline": "Underline concierge link (boolean)",
      "conciergeIcon": "Show icon on concierge link (boolean)"
    },
    "group_template": {
      "combineGroups": "Combine multiple groups into one (boolean)",
      "combinedTitleOverride": "Override title for combined groups",
      "slateOverride": "Override slate/count label",
      "customBlurb": "Custom marketing blurb text",
      "autoFillHeaderDate": "Auto-fill header with date range (boolean)",
      "layout_style": "'list-minimal' | 'list-detailed' | 'two-column-table' | 'magazine-hero' | 'sports-outline' | 'card-grid' | 'timeline' | 'calendar-strip' | 'bio-split' | 'combined-block'"
    }
  },

  "example_templates": {
    "html_template_example": "<div style=\"background: {{backgroundColor}}; padding: 24px; font-family: {{fontBody}};\">\n  <h1 style=\"color: {{textColor}}; font-family: {{fontHeading}};\">{{eventName}}</h1>\n  <img src=\"{{imageUrl}}\" alt=\"{{eventName}}\" style=\"width: 100%; border-radius: 8px;\" />\n  <p style=\"color: {{accentColor}};\">{{eventDate}} at {{eventTime}}</p>\n  <p style=\"color: {{textColor}};\">{{venue}} • {{cityState}}</p>\n  <p style=\"color: {{textColor}};\">Starting at {{priceMin}}</p>\n  <a href=\"{{ticketLink}}\" style=\"background: {{ctaBackgroundColor}}; color: {{ctaTextColor}}; padding: 12px 24px; border-radius: 8px; text-decoration: none; display: inline-block;\">{{ctaText}}</a>\n  <p style=\"font-size: 12px; color: {{textColor}}; opacity: 0.7;\">Questions? <a href=\"{{conciergeEmail}}\">Email our concierge</a></p>\n</div>",
    "quick_share_template_example": "🎟️ {{eventName}}\n📅 {{eventDate}} at {{eventTime}}\n📍 {{venue}}, {{cityState}}\n💰 Starting at {{priceMin}}\n\n🔗 {{ticketLink}}\n\nQuestions? Reply to this text or email concierge@firstclasstixx.com",
    "group_html_template_example": "<div style=\"background: {{backgroundColor}};\">\n  <h1>{{groupTitle}}</h1>\n  <p>{{eventCount}} upcoming games</p>\n  {{#each events}}\n  <div class=\"event-card\">\n    <span>{{eventDateShort}}</span>\n    <span>{{matchup}}</span>\n    <span>from {{priceMin}}</span>\n  </div>\n  {{/each}}\n</div>"
  },

  "template_example": {
    "templates": [
      {
        "name": "My Custom Template",
        "category": "concerts",
        "description": "A custom concert template with neon styling",
        "style_tags": ["neon", "dark"],
        "theme_mode": "dark",
        "layout_type": "individual",
        "config": {
          "fontHeading": "Oswald",
          "fontBody": "DM Sans",
          "fontSizeTitle": 32,
          "fontSizeBody": 14,
          "fontSizeSubtitle": 18,
          "letterSpacing": 0,
          "lineHeight": 1.5,
          "backgroundColor": "#1a1a1a",
          "textColor": "#ffffff",
          "accentColor": "#ff00ff",
          "ctaBackgroundColor": "#ff00ff",
          "ctaTextColor": "#ffffff",
          "borderColor": "#333333",
          "padding": 24,
          "margin": 16,
          "borderWidth": 0,
          "borderRadius": 8,
          "shadowIntensity": 0,
          "columnLayout": "single",
          "showImages": true,
          "showTimes": true,
          "showVenue": true,
          "showCta": true,
          "showConciergeLink": true,
          "showPrices": true,
          "ctaText": "Get Tickets",
          "ctaLink": "mailto:concierge@firstclasstixx.com"
        },
        "html_template": "<div style=\"background: {{backgroundColor}}; padding: {{padding}}px;\">\n  <h1 style=\"color: {{textColor}};\">{{eventName}}</h1>\n  <img src=\"{{imageUrl}}\" alt=\"{{eventName}}\" />\n  <p>{{eventDate}} • {{eventTime}}</p>\n  <p>{{venue}}, {{cityState}}</p>\n  <a href=\"{{ticketLink}}\">{{ctaText}}</a>\n</div>",
        "quick_share_template": "🎵 {{eventName}}\n📅 {{eventDate}} at {{eventTime}}\n📍 {{venue}}\n🎟️ {{ticketLink}}"
      }
    ]
  },

  "categories": [
    "sports",
    "concerts",
    "festivals",
    "big-events",
    "comedy",
    "theater",
    "tennis",
    "golf",
    "racing",
    "fighting",
    "awards",
    "parking",
    "wristbands",
    "upgrades",
    "hospitality",
    "minimal",
    "modern",
    "neon",
    "luxury",
    "general"
  ],

  "layout_types": [
    "individual",
    "group",
    "add-on"
  ],

  "style_tags": [
    "neon",
    "gradient",
    "minimal",
    "bold",
    "elegant",
    "retro",
    "futuristic",
    "brutalist",
    "glass",
    "team-branded",
    "dark",
    "light",
    "colorful",
    "monochrome"
  ],

  "add_on_types": [
    "parking",
    "vip-parking",
    "wristband-ga",
    "wristband-vip",
    "wristband-platinum",
    "wristband-weekend",
    "shuttle",
    "camping",
    "glamping",
    "meet-greet",
    "early-entry",
    "backstage",
    "lounge-access",
    "club-suite",
    "all-inclusive",
    "merch-bundle",
    "upgrade"
  ]
} as const;

export type TemplateImportSchemaType = typeof TEMPLATE_IMPORT_SCHEMA;
